# Generated by Django 2.0.13 on 2020-07-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20200723_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='age',
        ),
    ]
